# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
   
    - name: Extract pom details
      id: extract
      uses: andreacomo/maven-gav-extractor@v2.0.1
    - name: Log GAV
      run: |
        echo ${{ steps.extract.outputs.group-id }}
        echo ${{ steps.extract.outputs.artifact-id }}
        echo ${{ steps.extract.outputs.version }}
        echo ${{ steps.extract.outputs.name }}
      shell: bash
    
    - name: Build with Maven
      run: mvn -DskipTests=true -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -DskipTests=true deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.MVN_PKG_UPLOAD }}


    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1.3.2
      with:
        #subject-name: ${{  steps.lower-repo.outputs.githubowner }}/${{ steps.extract.outputs.artifact-id}}
        subject-path: ./target/**
        #subject-digest: ${{ steps.maven-deploy.outputs.digest }}
        #push-to-registry: true          
